# javascript_compressor: closure
# compressor_options:
#   compilation_level: "ADVANCED_OPTIMIZATIONS"

template_extension: ejs
template_function: _.template
  
javascripts:
  deps:
    - bower_components/jquery/dist/jquery.js
    - bower_components/underscore/underscore.js
    - bower_components/backbone/backbone.js
  templates:
    - app/scripts/templates/**/*.ejs
  scripts:
    - app/scripts/main.js
    - app/scripts/models/*.js
    - app/scripts/collections/*.js
    - app/scripts/views/**/*.js
    - app/scripts/routes/*.js

stylesheets:
  styles:
    - public/css/main.css